image: registry.sprd.net/sprd/ci/maven-oraclejdk-8:3.2.5

variables:
  # This will supress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors  --show-version"

# Cache downloaded dependencies and plugins between builds.
cache:
  key: "$CI_PROJECT_ID"
  paths:
    - .m2/repository

stages:
  - build
  - test
  - check
  - package
  - deploy
  - release

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPT $MAVEN_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS $MAVEN_OPTS test

package:
  stage: package
  script:
    - mvn $MAVEN_CLI_OPTS $MAVEN_OPTS -DskipTests=true deploy
